name: environment
channels:
  - pyviz
  - anaconda
  - conda-forge
  - defaults
dependencies:
 - numpy=1.20.2
 - holoviews=1.14.4=py_0
 - xarray=0.18.0=py_0
 - glob2=0.7p
 - pathlib2=2.3.5
 - pandas=1.2.4
 - panel=0.11.3
 - bokeh=2.3.2
 - scipy=1.6.2
 - hvplot=0.7.2
 - netcdf4=1.5.3
 - matplotlib=3.3.4
 - dask=2021.6.0
 - dask-core=2021.6.0
